# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=1)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('grade', models.CharField(max_length=1)),
                ('round_nr', models.IntegerField(default=0)),
                ('nr_of_questions', models.IntegerField(default=0)),
                ('answer_key', models.CharField(default='', max_length=100)),
                ('weights', models.CharField(default='', max_length=100)),
                ('cutoff', models.IntegerField(default=0)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('ans1', models.CharField(default='', max_length=100)),
                ('ans2', models.CharField(default='', max_length=100)),
                ('ans3', models.CharField(default='', max_length=100)),
                ('kt', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('points1', models.IntegerField(default=0)),
                ('points2', models.IntegerField(default=0)),
                ('points3', models.IntegerField(default=0)),
                ('index', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Student_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kt', models.CharField(max_length=200)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Info_temp')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='groups',
            field=models.ManyToManyField(to='skraning.Group'),
        ),
    ]
