# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kt', models.CharField(max_length=11)),
                ('points1', models.IntegerField(default=0)),
                ('points2', models.IntegerField(default=0)),
                ('points3', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Group')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Group'),
        ),
    ]
