# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='group',
        ),
        migrations.AddField(
            model_name='contact',
            name='group',
            field=models.ManyToManyField(to='skraning.Group'),
        ),
    ]
