# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0002_auto_20170723_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Zontact',
        ),
    ]
