# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0002_auto_20180124_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('index', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('returned', models.BooleanField(default=False)),
                ('active', models.IntegerField(default=0)),
                ('results', models.CharField(default='', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Group')),
            ],
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='results',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Round'),
        ),
    ]
