# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0004_auto_20170723_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='group',
            new_name='groups',
        ),
    ]
