# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0005_auto_20170724_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ans1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='ans2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='ans3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
