# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0006_auto_20170814_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('round_nr', models.IntegerField(default=0)),
                ('answer_key', models.CharField(max_length=100)),
            ],
        ),
    ]
