# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0007_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='cutoff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='nr_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='weights',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='round',
            name='answer_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
