# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0008_auto_20171013_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.RemoveField(
            model_name='round',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=700, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='grade',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_nr',
            field=models.IntegerField(default=0, primary_key=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='kt',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
