# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0009_auto_20171227_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
