# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0010_auto_20171227_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='index',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='index',
            field=models.CharField(max_length=200),
        ),
    ]
