# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0011_auto_20180103_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index',
            field=models.CharField(max_length=200),
        ),
    ]
