# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skraning', '0012_auto_20180103_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=200)),
                ('index', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kt', models.CharField(max_length=200)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skraning.Info_temp')),
            ],
        ),
    ]
